[package]
name = "parquet_metadata"
version = "0.1.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arrow = "29.0.0"
base64 = "0.13.0"
clap = { version = "3.2.22", features = ["derive", "std"], default-features = false }
parquet = "28.0.0"
