on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

name: Verify Code
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - run: |
          cargo clippy --no-deps --message-format=short >clippy_output.txt 2>&1

      - uses: LouisBrunner/checks-action@v1.1.1
        if: always()
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Clippy
          conclusion: ${{ job.status }}
          output: |
            {"summary":"Clippy results" }
          output_text_description_file: "clippy_output.txt"
