on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

name: Verify Code
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: LouisBrunner/checks-action@v1.1.1
        if: always()
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Test XYZ
          conclusion: ${{ job.status }}
          output: |
            {"summary":${{ steps.test.outputs.summary }}}

