on:
  release:
    types: [created]

jobs:
  upload-assets:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-20.04
            target: x86_64-unknown-linux-gnu
            use-cross: false

          - os: ubuntu-20.04
            target: aarch64-unknown-linux-gnu
            use-cross: true

          - os: windows-latest
            target: x86_64-pc-windows-msvc
            use-cross: false

          - os: macos-latest
            target: aarch64-apple-darwin
            use-cross: true

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: clippy, rustfmt
          override: true

      - name: (Optionally) install cross compilation tools
        if: ${{ matrix.use-cross 'true'}}
        run: |
          rustup target add ${{ matrix.target }}

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          use-cross: ${{ matrix.use-cross }}
          args: --release --target ${{ matrix.target }}

      - name: Upload
        uses: taiki-e/upload-rust-binary-action@v1
        with:
          bin: parquet_metadata
          leading_dir: true
          archive: $bin-$tag-$target
          token: ${{ secrets.GITHUB_TOKEN }}
