on:
  release:
    types: [created]

jobs:
  upload-assets:
    strategy:
      matrix:
        include:
          - os: ubuntu-20.04
            target: x86_64-unknown-linux-gnu
            use_cross: false

          - os: ubuntu-20.04
            target: aarch64-unknown-linux-gnu
            use_cross: true

          - os: windows-latest
            target: x86_64-pc-windows-msvc
            use_cross: false

          - os: macos-latest
            target: aarch64-apple-darwin
            use_cross: true

    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: clippy, rustfmt
          override: true

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          use_cross: ${{ matrix.use_cross }}
          target: ${{ matrix.target }}
          args: --release

      - name: Upload
        uses: taiki-e/upload-rust-binary-action@v1
        with:
          bin: parquet_metadata
          leading_dir: true
          archive: $bin-$tag-$target
          token: ${{ secrets.GITHUB_TOKEN }}
